import os
import subprocess
import string
import time
from hyprpy import Hyprland
from config import config
import global_var
import textwrap
import xml.etree.ElementTree as ET

class HyprlandPlugin():
    @staticmethod
    def hyprctl_autoreload_disabled():
        cmd_str = "hyprctl getoption misc:disable_autoreload"
        result = subprocess.run(cmd_str.split(), capture_output=True, text=True)
        # Parse hyprctl output robustly. Example output contains tokens
        # like '1' or 'true' when disabled.
        parts = result.stdout.strip().lower().split()
        if '1' in parts or 'true' in parts:
            return True
        return False
    @staticmethod
    def disable_hyprctl_auto_reload():
        subprocess.run(['hyprctl', 'misc', 'disable_autoreload', 'true'])
    @staticmethod
    def enable_hyprctl_auto_reload():
        subprocess.run(['hyprctl', 'misc', 'disable_autoreload', 'false'])
    @staticmethod
    def reload_hyprland():
        subprocess.run(['hyprctl', 'reload'])
    
    @staticmethod
    def active_window_class():
        try:
            hypr = Hyprland()
            try:
                active_window = hypr.get_active_window()
            except Exception:
                return None

            if not active_window:
                return None

            # Prefer attribute access; some hyprpy versions may return
            # objects without the expected attributes — guard accordingly.
            wm_class = getattr(active_window, 'wm_class', None)
            if wm_class is None:
                try:
                    wm_class = active_window.get('wm_class')
                except Exception:
                    wm_class = None

            return wm_class
        except Exception:
            return None
    @staticmethod
    def toggle_config_file():
        """ This is a hack to trigger the bindings in hyprland. By using soft link, we can change the destined config file by linking it either to the inkscape config file or a blank config file. """
        try:
            if global_var.IS_INKSCAPE_ACTIVE:
                subprocess.run(['hyprctl', 'dispatch', 'submap', 'Inkscape'])
            else:
                subprocess.run(['hyprctl', 'dispatch', 'submap', 'reset'])
            time.sleep(0.3) # Give it a moment to apply the submap change
        except FileNotFoundError:
            # if the destination doesn't exist for removal, ignore
            pass
        return global_var.IS_INKSCAPE_ACTIVE
    
    @staticmethod
    def keybind_to_hyprland(keybind):
        """ Convert the keybinds to hyprland config format and write to the config file. Keybinds are in the format of "Ctrl+Shift+v" or "Space". Hyprland config format is in the format of "bind = CTRL SHIFT, v, exec, echo -n \"Ctrl+Shift+v\" | nc localhost 65432". """
        parts = keybind.split('+')
        modifiers = []
        key = None
        for part in parts:
            part = part.strip()
            if part.lower() in ['ctrl', 'control']:
                modifiers.append('CTRL')
            elif part.lower() in ['shift']:
                modifiers.append('SHIFT')
            elif part.lower() in ['alt']:
                modifiers.append('ALT')
            elif part.lower() in ['super', 'win', 'meta']:
                modifiers.append('SUPER')
            else:
                key = part
        modifier_str = ' '.join(modifiers)
        if modifier_str:
            return f"{modifier_str}, {key}"
        else:
            return f" , {key}"
        
    @staticmethod
    def generate_hyprland_config():
        conf_str = textwrap.dedent("""
        # This is an auto generated config file for Inkscape Shortcut Manager. Do not edit this file directly, as it will be overwritten. Instead, edit the keybindings in Inkscape and run the manager with --generate-config to regenerate this file.

        # The following bindings are generated based on the keybindings found in Inkscape. They will send the keybinding string to the manager via netcat when pressed, but only when Inkscape is active.
        
        submap = Inkscape
        """)
        
        for key in list(string.ascii_lowercase):
            conf_str += f"bind = , {key}, exec, echo -n \"{key}\" | nc localhost {config['socket_port']}\n"
        for key in list(string.ascii_lowercase):
            conf_str += f"bindr = SHIFT, {key}, exec, echo -n \"SHIFT+{key}\" | nc localhost {config['socket_port']}\n"
        conf_str += f"bind = , Space, exec, echo -n \"Space\" | nc localhost {config['socket_port']}\n"
        conf_str += textwrap.dedent("""
        bind = ALT, I, submap, reset
        submap = reset
        """)
        return conf_str
    
    @staticmethod
    def keybind_to_wtype(keybind):
        """ Convert the keybinds to wtype format (string list). Keybinds are in the format of "Ctrl+Shift+v" or "Space". wtype format is in the format of "-M ctrl -M shift v -m ctrl -m shift" for "Ctrl+Shift+v" and " " for "Space". """
        parts = keybind.split('+')
        modifiers = []
        key = None
        for part in parts:
            part = part.strip()
            if part.lower() in ['ctrl', 'control']:
                modifiers.append('-M ctrl')
            elif part.lower() in ['shift']:
                modifiers.append('-M shift')
            elif part.lower() in ['alt']:
                modifiers.append('-M alt')
            elif part.lower() in ['super', 'win', 'meta']:
                modifiers.append('-M super')
            else:
                key = f"-k {part}"
        modifier_str = ' '.join(modifiers)
        if modifier_str:
            modifiers_str_release = ' '.join(m.replace('-M', '-m') for m in modifiers)
            modifier_str = f"{modifier_str} {key} {modifiers_str_release}"
            print(["wtype"] + modifier_str.split())
            return ["wtype"] + modifier_str.split()
        else:
            return ["wtype"] + f"{key}".split()
    
    @staticmethod
    def get_clipboard_content(target=None):
        """ Get the clipboard content for a specific target using wl-paste. If target is None, get the default clipboard content. """
        cmd = ["wl-paste", "-t"]
        if target:
            cmd.extend([target])
        try:
            result = subprocess.run(cmd, capture_output=True, text=True, timeout=5.0)
        except subprocess.TimeoutExpired:
            result = subprocess.CompletedProcess(args=cmd, returncode=1, stdout="", stderr="Timed out")
        time.sleep(0.5) # Wait a moment for clipboard to be populated
        return result.stdout.strip()
    
class SVGPlugin():
    @staticmethod
    def extract_tspan_text(svg_xml: str) -> str:
        """
        Extract the text content of the first <tspan> element from an SVG string.

        Args:
            svg_xml: SVG document as a string.

        Returns:
            The text inside the tspan, or empty string if no tspan is found.
        """
        # Register SVG namespace (default)
        ET.register_namespace('', 'http://www.w3.org/2000/svg')
        root = ET.fromstring(svg_xml)
        ns = {'svg': 'http://www.w3.org/2000/svg'}
        tspan = root.find('.//svg:tspan', ns)
        if tspan is None:
            return ""
        text = tspan.text
        return text
    
    @staticmethod
    def change_tspan_content(svg_xml: str, new_content: str):
        """
        Change the text content of the first <tspan> element within the first <g> element in an SVG string.

        Args:
            svg_xml: SVG document as a string.
            new_content: New text content to set in the <tspan>.
        Returns:
            Modified SVG document as a string.
        """
        # Parse the SVG and locate the first <g> element, then the first <tspan>
        try:
            ET.register_namespace('', 'http://www.w3.org/2000/svg')
            root = ET.fromstring(svg_xml)
        except Exception:
            return svg_xml

        ns = {'svg': 'http://www.w3.org/2000/svg'}
        g = root.find('.//svg:g', ns)
        if g is None:
            return svg_xml

        tspan = g.find('.//svg:tspan', ns)
        if tspan is not None:
            tspan.text = new_content
            try:
                return ET.tostring(root, encoding='unicode')
            except Exception:
                # Fallback: return original if serialization fails
                return svg_xml
        else:
            return svg_xml
